### ISSUE TITLE
Purpose of additional logs at normal log level?

### ISSUE THREAD

**Issue by nh2** [rapier1/openssh-portable#25] opened 2020-09-23 19:55 UTC
When using the patch set as a drop-in for openssh, all SSH connections (e.g. invoked directly via SSH or via `rsync`) print additional stuff into the terminal:

```
SSH: Server;Ltype: Version;Remote: 1.2.3.4-22;Protocol: 2.0;Client: OpenSSH_8.2
```

This is from e.g.

https://github.com/rapier1/openssh-portable/commit/f2341a194a45440ed04a66aa7310ee0d929c1ef3#diff-cc9e833353f4432391cb4c8463c0a2beR1357

Is that intended?

Would it make sense to turn it off, so that you use the patched `ssh` for scripting without getting additional output printed?

**Comment by rapier1** [comment] 2020-09-24 15:37
It is not intended. My apologies for that. I thought I had pushed the changes to fix that issue. I will do that shortly and update the tags.

**Comment by rapier1** [comment] 2020-09-24 17:46
As an aside - this was caused by changes in OpenSSH (specifically moving the key exchange from an sshd function to a generic kex (key exchange function). When a log command is issued on the client side it is, by default, sent to STDOUT. You can have that redirected to syslog by using the -y option. That said, I had code to determine if the kex was happening on the client side and to squelch log message. Somehow I lost it (probably forgot to do a push) so I'll need to recreate it.

**Comment by rapier1** [comment] 2020-09-24 18:21
Okay, all fixed in git. I'll push the changes out to sourceforge soon. Sorry about this oversight. 

I also fixed a linking error for gcc10 as an added bonus.

**Closed** 2020-09-24 18:26 UTC

**Comment by nh2** [comment] 2020-09-24 21:37
@rapier1 Thanks, much appreciated!

Is the place in https://github.com/rapier1/openssh-portable/commit/dd8b44b5f0157ec9304ad9caabc4ca5a3bd7351c the only one that needs to be handled though?

I found 4 logs that looked like this in the code: https://github.com/nh2/openssh-portable/commit/a7fb26a4685e871a6ca54fbdb9b3c6a14493192a

**Comment by rapier1** [comment] 2020-09-24 21:51
It should be. If the function 'logit' is called on the client side the default is to send it to STDOUT unless you use -E to append it to a file or -y to send it to syslog. So change I made is the only place where sending HPN related information to the syslog could end up being called by the client. There are other locations where OpenSSH might send syslog information on the client side but that's outside of my scope.
